@startuml Household Registry - Create
!theme vibrant
participant Client as c
participant HouseholdRegistry as hr
queue Kafka as k
participant PersisterService as prs
participant IndexerService as idx
participant ErrorService as es
participant ElasticSearch as el
database Database as db
c -> hr : /household/v1/_create
activate hr
hr -> hr: Validate request body
alt request validation fails
    hr -> hr: Request validation failed
    hr -> k: Household Data /error_topic
    note left
        This will be marked as unrecoverable right away 
        and requhre manual intervention
    end note
    activate k
    group async
        es -> k: Consume Household Data
        activate es
        deactivate k
        es -> db: Persist Household Data /error_table
        activate db
        deactivate db
        deactivate es
    end
    hr -> c: HttpStatus: 200 OK with appropriate response code
end
hr -> hr: Request validation successful
hr -> db: Check if the record already exists
alt record already exists
    activate db
    db -> hr: 1 row
    hr -> c: HttpStatus: 200 OK with appropriate response code
end
db -> hr: 0 rows
deactivate db
alt individual doesn't exists
    hr -> db: Check if individual exists
    activate db
    db -> hr: 0 rows
    deactivate db
    hr -> k: Household Data /error_topic
    note left
        This will be marked as recoverable and will be 
        retried later
    end note
    activate k
    group async
        es -> k: Consume Household Data
        activate es
        deactivate k
        es -> db: Persist Household Data /error_table
        activate db
        deactivate db
        deactivate es
    end
    hr -> c: HttpStatus: 200 OK with appropriate response code
end
hr -> db: Check if individual exists
activate db
db -> hr: 1 row
deactivate db
hr -> k: Household Data /persist_topic
activate k
hr -> c: HttpStatus: 200 OK
deactivate hr
group async
    prs -> k: Consume Household Data
    activate prs
    idx -> k: Consume Household Data
    activate idx
    idx -> el: Store Household Data
    activate el
    deactivate el
    deactivate idx
    prs -> db: Persist Household Data
    activate db
    deactivate db
    deactivate prs
end
deactivate k
@enduml