@startuml Household Registry - Update
!theme vibrant
participant Client as c
participant HouseholdRegistry as hr
participant RedisCache as rc
queue Kafka as k
participant PersisterService as prs
participant IndexerService as idx
participant ErrorService as es
participant ElasticSearch as el
database Database as db
c -> hr : /household/v1/_update
activate hr
hr -> hr: Validate request body
alt request validation fails
    hr -> hr: Request validation failed
    hr -> k: Household Data /error_topic
    note left
        This will be marked as unrecoverable right away 
        and require manual intervention
    end note
    activate k
    group async
        es -> k: Consume Household Data
        activate es
        deactivate k
        es -> db: Persist Household Data /error_table
        activate db
        deactivate db
        deactivate es
    end
    hr -> c: HttpStatus: 202 ACCEPTED with appropriate response code
end
hr -> hr: Request validation successful
alt record doesn't exist
    hr -> rc: Fetch the existing record
    activate rc
    rc -> rc: 0 rows
    rc -> db: Fetch the existing record
    activate db
    db -> rc: 0 rows
    deactivate db
    rc -> hr: 0 rows
    deactivate rc
    note left
        This will be marked as unrecoverable right away 
        and require manual intervention
    end note
    hr -> k: Household Data /error_topic
    group async
        es -> k: Consume Household Data
        activate es
        deactivate k
        es -> db: Persist Household Data /error_table
        activate db
        deactivate db
        deactivate es
    end
    hr -> c: HttpStatus: 202 ACCEPTED with appropriate response code
end
alt record doesn't exists in cache
    hr -> rc: Fetch the existing record
    activate rc
    rc -> rc: 0 rows
    rc -> db: Fetch the existing record
    activate db
    db -> rc: 1 row
    deactivate db
    rc -> hr: 1 row
    deactivate rc
end
hr -> rc: Fetch the existing record
activate rc
rc -> hr: 1 row
deactivate rc
hr -> hr: Check if the new record is not equal to existing record
alt new record equals existing record
    hr -> hr: new record equals existing record
    hr -> c: HttpStatus: 202 ACCEPTED with appropriate response code
end
hr -> k: Household Data /update_topic
activate k
hr -> rc: Put new record in cache
activate rc
deactivate rc
hr -> c: HttpStatus: 202 ACCEPTED
deactivate hr
group async
    prs -> k: Consume Household Data
    activate prs
    idx -> k: Consume Household Data
    activate idx
    idx -> el: Store Household Data
    activate el
    deactivate el
    deactivate idx
    prs -> db: Update Household Data
    activate db
    deactivate db
    deactivate prs
end
deactivate k
@enduml