swagger: '2.0'
info:
  version: 1.0.0
  title: Household Registry
  description: >
    This module facilitates maintenance of a household registry.
  contact:
    name: Digit
    email: info@egovernments.org
schemes:
  - https
x-common-path: >-
  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml
paths:
  /household/v1/_create:
    post:
      summary: >-
        Create/Add a new household
      description: >-
        Create a new household
      parameters:
        - name: Household
          in: body
          description: Capture details of Household.
          required: true
          schema:
            $ref: '#/definitions/HouseholdRequest'
        - $ref: '#/parameters/echoResource'
      tags:
        - Household
      responses:
        '202':
          description: Accepted
          schema:
            $ref: '#/definitions/HouseholdResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /household/v1/_update:
    post:
      summary: >-
        Update the details of a existing household
      description: >-
        Update the details of a existing household
      parameters:
        - name: Household
          in: body
          description: Details for existing household.
          required: true
          schema:
            $ref: '#/definitions/HouseholdRequest'
        - $ref: '#/parameters/echoResource'
      tags:
        - Household
      responses:
        '202':
          description: Accepted
          schema:
            $ref: '#/definitions/HouseholdResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /household/v1/_search:
    post:
      summary: >-
        Search existing household
      description: >-
        Search existing household
      parameters:
        - name: Household
          in: body
          description: Details for existing household.
          required: true
          schema:
            $ref: '#/definitions/HouseholdSearchRequest'
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/tenantId'
        - $ref: '#/parameters/lastChangedSince'
        - $ref: '#/parameters/includeDeleted'
      tags:
        - Household
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/HouseholdResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes

  /household/member/v1/_create:
    post:
      summary: >-
        Add a new household member
      description: >-
        Add a new member to household
      parameters:
        - name: HouseholdMember
          in: body
          description: Capture linkage of Household to Member.
          required: true
          schema:
            $ref: '#/definitions/HouseholdMemberRequest'
        - $ref: '#/parameters/echoResource'
      tags:
        - Household
      responses:
        '202':
          description: Accepted
          schema:
            $ref: '#/definitions/HouseholdMemberResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /household/member/v1/_update:
    post:
      summary: >-
        Update the linkage details of an existing household member
      description: >-
        Update the linkage details of an existing household member
      parameters:
        - name: HouseholdMember
          in: body
          description: Linkage details for existing household member.
          required: true
          schema:
            $ref: '#/definitions/HouseholdMemberRequest'
        - $ref: '#/parameters/echoResource'
      tags:
        - Household
      responses:
        '202':
          description: Accepted
          schema:
            $ref: '#/definitions/HouseholdResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /household/member/v1/_search:
    post:
      summary: >-
        Search existing household member
      description: >-
        Search existing household member
      parameters:
        - name: HouseholdMember
          in: body
          description: Details for existing household member.
          required: true
          schema:
            $ref: '#/definitions/HouseholdMemberSearchRequest'
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/tenantId'
        - $ref: '#/parameters/lastChangedSince'
        - $ref: '#/parameters/includeDeleted'
      tags:
        - Household
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/HouseholdMemberResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes


parameters:
  #TODO is tenantId required as a query param if it can be determine from requestInfo->userInfo
  tenantId:
    name: tenantId
    in: query
    description: Unique id for a tenant.
    required: true
    type: string
    format: varchar

  lastChangedSince:
    name: lastChangedSince
    description: |
      epoch of the time since when the changes on the object should be picked up. Search results from this parameter should include both newly created objects since this time as well as any modified objects since this time. This criterion is included to help polling clients to get the changes in system since a last time they synchronized with the platform.
    in: query
    required: false
    type: integer
    format: int64

  echoResource:
    name: echoResource
    in: query
    type: boolean
    required: false
    default: true
    description: Client can specify if the resource in request body needs to be sent back in the response. This is being used to limit amount of data that needs to flow back from the server to the client in low bandwidth scenarios. Server will always send the server generated id for validated requests.

  serverHandlesErrors:
    name: serverHandlesErrors
    in: query
    type: boolean
    required: false
    default: false
    description: Client can specify that it is incapable of handling any errors with the requests and server should route these for manual intervention if required.

  limit:
    name: limit
    description: Pagination - limit records in response
    in: query
    type: integer
    minimum: 0
    maximum: 1000 #TODO review
    required: true

  offset:
    name: offset
    description: Pagination - offset from which records should be returned in response
    in: query
    type: integer
    minimum: 0
    required: true

  includeDeleted:
    name: includeDeleted
    description: Used in search APIs to specify if (soft) deleted records should be included in search results.
    in: query
    type: boolean
    default: false
    required: false

definitions:
  boundaryCode:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/boundaryCode'
  id:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/id'
  idForSearch:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/idForSearch'
  clientReferenceId:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/clientReferenceId'
  tenantId:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/tenantId'
  eventTimestamp:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/eventTimestamp'
  isDeleted:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/isDeleted'
  rowVersion:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/rowVersion'
  apiOperation:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/apiOperation'
  additionalFields:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/additionalFields'
  Address:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/Address'

  memberCount:
    type: integer
    example: 4
    minimum: 0
    maximum: 1000
    description: Total no of individuals in a household. Could be different from the count of members as all members may not be enumerated individually.

  Household:
    description: A representation of Household.
    type: object
    required:
      - memberCount
    properties:
      id:
        $ref: '#/definitions/id'
      tenantId:
        $ref: '#/definitions/tenantId'
      clientReferenceId:
        $ref: '#/definitions/clientReferenceId'
      memberCount:
        $ref: '#/definitions/memberCount'
      address:
        $ref: '#/definitions/Address'
      #      members:
      #        type: array
      #        items:
      #          $ref: '#/definitions/HouseholdMember'
      additionalFields:
        $ref: '#/definitions/additionalFields'
      isDeleted:
        $ref: '#/definitions/isDeleted'
      rowVersion:
        $ref: '#/definitions/rowVersion'
      auditDetails:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/AuditDetails'

  HouseholdSearch:
    description: A representation of Household.
    type: object
    properties:
      id:
        $ref: '#/definitions/idForSearch'
      tenantId:
        $ref: '#/definitions/tenantId'
      clientReferenceId:
        $ref: '#/definitions/clientReferenceId'
      memberCount:
        $ref: '#/definitions/memberCount'
      boundaryCode:
        $ref: '#/definitions/boundaryCode'

  HouseholdMember:
    description: A representation of a household member (already registered as an individual)
    type: object
    required:
      - householdId
      - individualId
    properties:
      id:
        $ref: '#/definitions/id'
      householdId:
        $ref: '#/definitions/id'
      householdClientReferenceId:
        $ref: '#/definitions/clientReferenceId'
      individualId:
        $ref: '#/definitions/id'
      individualClientReferenceId:
        $ref: '#/definitions/clientReferenceId'
      isHeadOfHousehold:
        type: boolean
        default: false
      tenantId:
        $ref: '#/definitions/tenantId'
      additionalFields:
        $ref: '#/definitions/additionalFields'
      isDeleted:
        $ref: '#/definitions/isDeleted'
      rowVersion:
        $ref: '#/definitions/rowVersion'
      auditDetails:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/AuditDetails

  HouseholdMemberSearch:
    description: Search model for household member
    type: object
    properties:
      id:
        $ref: '#/definitions/idForSearch'
      householdId:
        $ref: '#/definitions/idForSearch'
      householdClientReferenceId:
        $ref: '#/definitions/clientReferenceId'
      individualId:
        $ref: '#/definitions/idForSearch'
      individualClientReferenceId:
        $ref: '#/definitions/clientReferenceId'
      isHeadOfHousehold:
        type: boolean
      tenantId:
        $ref: '#/definitions/HouseholdMember/properties/tenantId'

  HouseholdRequest:
    type: object
    properties:
      RequestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/RequestInfo
      Household:
        type: array
        minItems: 1
        items:
          $ref: '#/definitions/Household'
      apiOperation:
        $ref: '#/definitions/apiOperation'
    required:
      - RequestInfo
      - Household

  HouseholdSearchRequest:
    type: object
    properties:
      RequestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/RequestInfo
      Household:
        $ref: '#/definitions/HouseholdSearch'
    required:
      - RequestInfo
      - Household

  HouseholdResponse:
    type: object
    properties:
      ResponseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ResponseInfo
      Household:
        type: array
        items:
          $ref: '#/definitions/Household'
    required:
      - ResponseInfo

  HouseholdMemberRequest:
    type: object
    properties:
      RequestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/RequestInfo
      HouseholdMember:
        type: array
        minItems: 1
        items:
          $ref: '#/definitions/HouseholdMember'
      apiOperation:
        $ref: '#/definitions/apiOperation'
    required:
      - RequestInfo
      - HouseholdMember

  HouseholdMemberSearchRequest:
    type: object
    properties:
      RequestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/RequestInfo
      HouseholdMember:
        $ref: '#/definitions/HouseholdMemberSearch'
    required:
      - RequestInfo
      - HouseholdMember

  HouseholdMemberResponse:
    type: object
    properties:
      ResponseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ResponseInfo
      HouseholdMember:
        type: array
        items:
          $ref: '#/definitions/HouseholdMember'
    required:
      - ResponseInfo
